---
# tasks file for iptables
- name: include os-specific variables
  include_vars: "{{ansible_os_family}}.yml"

- name: include el5 variables
  include_vars: "{{ ansible_os_family }}5.yml"
  when: ansible_distribution_release == "Tikanga"

- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"
