---
- name: install iptables
  package: name={{ item }} state=installed
  with_items: "{{ iptables_pkgs }}"

- name: template iptables
  template: >-
      src=iptables.j2
      dest=/etc/iptables/rules.v4
      owner=root
      group=root
      mode=0600
      backup=yes
  notify: restart iptables

- name: template ip6tables
  template: >-
      src=ip6tables.j2
      dest=/etc/iptables/rules.v6
      owner=root
      group=root
      mode=0600
      backup=yes
  notify: restart iptables
  when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"

- name: template iptables service
  template: >-
    src=iptables.service.j2
    dest=/etc/systemd/system/iptables.service
    owner=root
    group=root
    mode=0644
    backup=yes

- name: enable and start iptables service
  service: name=iptables state=started enabled=yes
